### ISSUE TITLE
should fix install_zsh script

### ISSUE THREAD

**Issue by cartopy** [cih9088/dotfiles#2]
The link in install_zsh script (wget ~~~) is not correct since zsh-5.6.2 is out-date.

You may want to put "old" (/pub/ -> /pub/old/)

**Comment by cih9088** [comment]
The link is changed to `sourceforge` to get the latest version of zsh.
You can still specify version of zsh if you need.

**Comment by cartopy** [comment]
I miss you, Inhyuk

**Comment by cih9088** [comment]
zzzzzzzzzzz
I miss you as well. How is it going over there?
Did you get Porsche? 🚗

**Comment by cartopy** [comment]
ㅋㅋㅋㅋ 아니요 아직 포르쉐는.... 돈 좀 더 모아야죠 일시불로 사게 ㅋㅋㅋㅋ

나쁘진 않아요 다만 제가 더 잘해야죠.. ㅜㅜㅜ 영어 슈벌탱 ㅜㅜ

열심히 앤디의 환경을 쓰려고 하고 있습니다. 혹시 로컬배포판을 만드실 생각은 없습니까? ㅋㅋㅋㅋ 인터넷을 안쓰고도... 하하....

**Comment by cih9088** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
삼성같은 곳은 외부 package site 내부에 미러 해놓던데 야후는 그렇게 안되있어요?ㅋㅋㅋㅋ

**Comment by cartopy** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 그런 것 같은 기분입니다. 회사가... 안좋네요 ㅠㅠㅠㅠ

**Comment by cih9088** [comment]
좋은 회사인데 그런게 없다는게 신기하네요 🤔
이든 말 들어보니 회사가 기대만큼 만족스럽지 않나보군요 ㅠㅠㅜ

**Comment by cartopy** [comment]
음.. 회사는 만족스럽습니다. 다만 뭔가 기술적으로 엄청 프로페셔널한가? 싶은거죠 @_@ ㅋㅋㅋ

아마 제가 멍청하고 잘 몰라서 그럴거에요...

P.S. 오프라인 패키지 만들어주세요!!! ㅋㅋㅋㅋㅋㅋ

**Comment by cih9088** [comment]
아니 이미 오-썸하신분이 그러시면 다른 사람들은 어떻게 사나요ㅋㅋㅋㅋ

오프라인 패키지는 제가 한번 시간날때 만들어보도록 하겠습니다ㅋㅋㅋ
